module(name = "roo_display", version = "3.3.0")

bazel_dep(name = "rules_cc", version = "0.2.25")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "roo_testing", version = "2.1.2")
bazel_dep(name = "roo_backport", version = "1.2.4")
bazel_dep(name = "roo_collections", version = "1.4.7")
bazel_dep(name = "roo_io", version = "2.3.0")
bazel_dep(name = "roo_icons", version = "1.2.4", dev_dependency = True)
bazel_dep(name = "roo_fonts_basic", version = "1.0.4", dev_dependency = True)
