load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "part1_1_basic_setup",
    sketch = "part1_1_basic_setup.ino",
    deps = ["//:roo_display"],
)
