cc_library(
    name = "reference_device",
    srcs = [
        "roo_display/fake/reference_device.cpp",
        "roo_display/fake/reference_device.h",
    ],
    deps = [
        "//:roo_display",
        "@roo_testing//roo_testing/transducers/ui/viewport",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
)
