name: CI

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build_and_test:
    uses: dejwk/roo_testing/.github/workflows/client-ci.yml@e51df12bcaf96e4270a459ead582767fdcd3a5ac # roo_testing 2.0.0
    with:
      profiles: '["arduino", "idf"]'
      run_tests: true
      system_packages: >-
        libunwind-dev binutils-dev libx11-dev libjpeg-dev libpng-dev zlib1g-dev
      extra_bazel_args: >-
        --copt=-DHAVE_SYMBOLIZE
        --copt=-DHAVE_UNWIND
        --copt=-DHAVE_LIBUNWIND
        --linkopt=-lunwind
        --linkopt=-ldl
